"""instrument master rich columns

Revision ID: debc9e15fc9b
Revises: 5a2843c19f71
Create Date: 2026-07-05 08:55:01.309567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'debc9e15fc9b'
down_revision: Union[str, None] = '5a2843c19f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('uid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('instruments', sa.Column('display_name', sa.String(length=80), nullable=True))
    op.add_column('instruments', sa.Column('segment', sa.String(length=20), nullable=True))
    op.add_column('instruments', sa.Column('instrument_type', sa.String(length=20), nullable=True))
    op.add_column('instruments', sa.Column('underlying', sa.String(length=40), nullable=True))
    op.add_column('instruments', sa.Column('tick_size', sa.DECIMAL(precision=12, scale=4), nullable=True))
    op.add_column('instruments', sa.Column('strike_step', sa.DECIMAL(precision=12, scale=2), nullable=True))
    op.add_column('instruments', sa.Column('expiry_rule', sa.String(length=40), nullable=True))
    op.add_column('instruments', sa.Column('vendor_symbols', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('instruments', sa.Column('snapshot_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('instruments', sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False))
    op.create_unique_constraint('uq_instruments_uid', 'instruments', ['uid'])
    # ### end Alembic commands ###

    # ── Backfill the rich master data for the existing NIFTY/SENSEX rows ──────
    # This is the "move the hardcoded dicts into the DB" step: the values below
    # previously lived in fyers_provider._SPOT_SYMBOLS/_OPTION_SYMBOLS, the
    # last-Thursday futures builder, mock_provider._STEP, options_math.LOT_SIZE,
    # and options_lab_service._SYMBOLS. Kept in sync with app/instruments/seed.py
    # (which INSERTs the same rows on a fresh DB). No-op if the rows are absent.
    op.execute("""
        UPDATE instruments SET
            display_name    = 'NIFTY 50',
            segment         = 'INDEX',
            instrument_type = 'INDEX',
            tick_size       = 0.05,
            strike_step     = 50,
            expiry_rule     = 'MONTHLY_LAST_THU',
            vendor_symbols  = '{"fyers": {"spot": "NSE:NIFTY50-INDEX", "option": "NSE:NIFTY50-INDEX", "futures_template": "NSE:NIFTY{yy}{mon}FUT"}}'::jsonb,
            snapshot_enabled = true,
            status          = 'ACTIVE'
        WHERE instrument_id = 1;
    """)
    op.execute("""
        UPDATE instruments SET
            display_name    = 'SENSEX',
            segment         = 'INDEX',
            instrument_type = 'INDEX',
            tick_size       = 0.05,
            strike_step     = 100,
            expiry_rule     = 'MONTHLY_LAST_THU',
            vendor_symbols  = '{"fyers": {"spot": "BSE:SENSEX-INDEX", "option": "BSE:SENSEX-INDEX", "futures_template": "BSE:SENSEX{yy}{mon}FUT"}}'::jsonb,
            snapshot_enabled = true,
            status          = 'ACTIVE'
        WHERE instrument_id = 2;
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_instruments_uid', 'instruments', type_='unique')
    op.drop_column('instruments', 'status')
    op.drop_column('instruments', 'snapshot_enabled')
    op.drop_column('instruments', 'vendor_symbols')
    op.drop_column('instruments', 'expiry_rule')
    op.drop_column('instruments', 'strike_step')
    op.drop_column('instruments', 'tick_size')
    op.drop_column('instruments', 'underlying')
    op.drop_column('instruments', 'instrument_type')
    op.drop_column('instruments', 'segment')
    op.drop_column('instruments', 'display_name')
    op.drop_column('instruments', 'uid')
    # ### end Alembic commands ###
