"""multi-tenant saas tables

Revision ID: 359a6ec8421d
Revises: a2aa386db8ed
Create Date: 2026-07-05 13:54:53.003341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.models  # provides app.db.models.UTCDateTime used below

# revision identifiers, used by Alembic.
revision: str = '359a6ec8421d'
down_revision: Union[str, None] = 'a2aa386db8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Reference data ────────────────────────────────────────────────────────────
_PERMISSIONS = [
    ("instrument.read", "Read instruments, quotes, chains"),
    ("dashboard.read",  "View dashboards"),
    ("options.read",    "View options analytics"),
    ("analytics.read",  "View analytics (OI, gamma, etc.)"),
    ("watchlist.write", "Create/edit watchlists"),
    ("alert.write",     "Create/edit alerts"),
    ("strategy.write",  "Create/edit strategies"),
    ("journal.write",   "Create/edit journal entries"),
    ("broker.connect",  "Connect a broker account"),
    ("member.manage",   "Invite/remove org members"),
    ("apikey.manage",   "Create/revoke API keys"),
    ("org.manage",      "Manage organization settings"),
    ("org.billing",     "Manage billing & subscription"),
]
_ROLES = [("owner", "Owner"), ("admin", "Admin"), ("analyst", "Analyst"), ("viewer", "Viewer")]
_READ = ["instrument.read", "dashboard.read", "options.read", "analytics.read"]
_ANALYST = _READ + ["watchlist.write", "alert.write", "strategy.write", "journal.write", "broker.connect"]
_ADMIN = _ANALYST + ["member.manage", "apikey.manage"]
_OWNER = _ADMIN + ["org.manage", "org.billing"]
_GRANTS = {"viewer": _READ, "analyst": _ANALYST, "admin": _ADMIN, "owner": _OWNER}
_PLANS = [
    # key, name, price_inr (paise), limits
    ("free",       "Free",       0,      '{"watchlists":1,"alerts":3,"api_keys":0,"live_data":false}'),
    ("pro",        "Pro",        49900,  '{"watchlists":25,"alerts":100,"api_keys":2,"live_data":true}'),
    ("desk",       "Desk",       249900, '{"watchlists":200,"alerts":1000,"api_keys":10,"live_data":true}'),
    ("enterprise", "Enterprise", 0,      '{"watchlists":-1,"alerts":-1,"api_keys":-1,"live_data":true}'),
]

# Org-scoped tables get RLS keyed on the request's app.tenant_id (set per request
# by get_db). NOTE: the app currently connects as a SUPERUSER role, which bypasses
# RLS — so app-layer scoping in the services is the primary enforcement today; these
# policies become active once deployed under a non-superuser role. The
# "IS NULL / '' " branch keeps system/bootstrap queries (no tenant set) working.
_RLS_TABLES = {
    "organizations": "id",
    "memberships":   "org_id",
    "api_keys":      "org_id",
    "subscriptions": "org_id",
}


def _seed() -> None:
    bind = op.get_bind()
    for key, desc in _PERMISSIONS:
        bind.execute(
            sa.text("INSERT INTO permissions (key, description) VALUES (:k, :d) "
                    "ON CONFLICT (key) DO NOTHING"),
            {"k": key, "d": desc},
        )
    for key, name in _ROLES:
        bind.execute(
            sa.text("INSERT INTO roles (key, name, is_system) VALUES (:k, :n, true) "
                    "ON CONFLICT (key) DO NOTHING"),
            {"k": key, "n": name},
        )
    for role_key, perms in _GRANTS.items():
        for perm_key in perms:
            bind.execute(
                sa.text(
                    "INSERT INTO role_permissions (role_id, permission_id) "
                    "SELECT r.id, p.id FROM roles r, permissions p "
                    "WHERE r.key = :rk AND p.key = :pk "
                    "ON CONFLICT DO NOTHING"
                ),
                {"rk": role_key, "pk": perm_key},
            )
    for key, name, price, limits in _PLANS:
        bind.execute(
            sa.text("INSERT INTO plans (key, name, price_inr, limits) "
                    "VALUES (:k, :n, :p, CAST(:l AS jsonb)) ON CONFLICT (key) DO NOTHING"),
            {"k": key, "n": name, "p": price, "l": limits},
        )


def _enable_rls() -> None:
    for tbl, col in _RLS_TABLES.items():
        op.execute(f"ALTER TABLE {tbl} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {tbl}_tenant_isolation ON {tbl}
            USING (
                current_setting('app.tenant_id', true) IS NULL
                OR current_setting('app.tenant_id', true) = ''
                OR {col} = current_setting('app.tenant_id', true)::uuid
            )
            """
        )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('price_inr', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('key', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('owner_user_id', sa.BIGINT(), nullable=False),
    sa.Column('plan_key', sa.String(length=20), server_default=sa.text("'free'"), nullable=False),
    sa.Column('is_personal', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(), nullable=False),
    sa.Column('deleted_at', app.db.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_org_owner', 'organizations', ['owner_user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('created_by', sa.BIGINT(), nullable=True),
    sa.Column('last_used_at', app.db.models.UTCDateTime(), nullable=True),
    sa.Column('revoked_at', app.db.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_org', 'api_keys', ['org_id'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', app.db.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_membership_org_user')
    )
    op.create_index('ix_membership_org', 'memberships', ['org_id'], unique=False)
    op.create_index('ix_membership_user', 'memberships', ['user_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('plan_key', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('provider', sa.String(length=20), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=True),
    sa.Column('current_period_end', app.db.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscriptions_org', 'subscriptions', ['org_id'], unique=False)
    # ### end Alembic commands ###

    _seed()          # roles, permissions, grants, plans (reference data)
    _enable_rls()    # deploy-ready tenant isolation policies


def downgrade() -> None:
    for tbl in _RLS_TABLES:
        op.execute(f"DROP POLICY IF EXISTS {tbl}_tenant_isolation ON {tbl}")
        op.execute(f"ALTER TABLE {tbl} DISABLE ROW LEVEL SECURITY")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subscriptions_org', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_membership_user', table_name='memberships')
    op.drop_index('ix_membership_org', table_name='memberships')
    op.drop_table('memberships')
    op.drop_index('ix_api_keys_org', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('role_permissions')
    op.drop_index('ix_org_owner', table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('roles')
    op.drop_table('plans')
    op.drop_table('permissions')
    # ### end Alembic commands ###
