"""broker_connections table

Revision ID: a2aa386db8ed
Revises: debc9e15fc9b
Create Date: 2026-07-05 09:38:45.695894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.db.models  # provides app.db.models.UTCDateTime used below

# revision identifiers, used by Alembic.
revision: str = 'a2aa386db8ed'
down_revision: Union[str, None] = 'debc9e15fc9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_connections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=True),
    sa.Column('broker', sa.String(length=20), nullable=False),
    sa.Column('access_token_enc', sa.TEXT(), nullable=True),
    sa.Column('refresh_token_enc', sa.TEXT(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('generated_at', app.db.models.UTCDateTime(), nullable=True),
    sa.Column('expires_at', app.db.models.UTCDateTime(), nullable=True),
    sa.Column('created_at', app.db.models.UTCDateTime(), nullable=False),
    sa.Column('updated_at', app.db.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_broker_conn_user_broker', 'broker_connections', ['user_id', 'broker'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_broker_conn_user_broker', table_name='broker_connections')
    op.drop_table('broker_connections')
    # ### end Alembic commands ###
