/*
================================================================================
  STRIKFIN — PostgreSQL Database Creation Script
  Database : StrikfinDB
  Engine   : PostgreSQL 16+  (tested on 18)
  Driver   : SQLAlchemy 2.0 async + asyncpg  (postgresql+asyncpg://)
  Auth     : role + password (set DB_USER / DB_PASSWORD in backend/.env)
================================================================================

  HOW TO USE (step by step)
  ─────────────────────────
  1. Make sure PostgreSQL 16+ is running and you know the port (default 5432).
  2. Create the database FIRST (this cannot be done from inside it):

         CREATE DATABASE "StrikfinDB";

     (Keep the double quotes — Postgres folds unquoted names to lowercase,
      so quoting preserves the capital S and D used by the app.)

  3. Connect to StrikfinDB, then run THIS script:
         • pgAdmin : select StrikfinDB → Query Tool → open this file → Run (F5)
         • psql    : psql -h localhost -p 5432 -U postgres -d StrikfinDB -f docs/postgres_db_creation.sql

  4. Point the app at it via backend/.env:
         DB_HOST=localhost
         DB_PORT=5432
         DB_NAME=StrikfinDB
         DB_USER=postgres
         DB_PASSWORD=your-postgres-password

  NOTE: In development the backend also auto-creates these tables from the ORM
  (app/db/models.py) on startup, and Alembic manages them in production. This
  script is the manual / reference equivalent and is safe to re-run (every
  statement uses IF NOT EXISTS / ON CONFLICT).

  TABLE INVENTORY (execution order — mirrors app/db/models.py)
  ───────────────────────────────────────────────────────────
  01. users
  02. refresh_tokens
  03. instruments                (seeded: NIFTY50, SENSEX)
  04. index_live_data
  05. option_chain_snapshots
  06. option_chain_rows
  07. institutional_activity
  08. news_feed
  09. market_sentiment
  10. smart_money_signals
  11. ai_trade_signals
  12. signal_outcomes
  13. audit_logs

  VIEWS
  ─────────────────────────
  V01. vw_latest_index_snapshot
  V02. vw_latest_option_snapshot
  V03. vw_daily_institutional_summary

  FUNCTIONS (maintenance — replace the old T-SQL stored procedures)
  ─────────────────────────
  F01. fn_cleanup_expired_tokens(retention_days INT)
  F02. fn_purge_old_snapshots(retain_days INT)

  DRIFT NOTE: the legacy MSSQL script also had a `market_regime` table +
  `vw_latest_regime` view, but there is no matching ORM model in models.py
  today, so they are intentionally omitted here. Reconcile in "Part 2"
  (re-add the ORM model or formally drop the feature) before relying on it.
================================================================================
*/

-- ============================================================================
-- 1. USERS
-- ============================================================================
CREATE TABLE IF NOT EXISTS users (
    user_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    display_name  VARCHAR(100),
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    last_login_at TIMESTAMP,

    CONSTRAINT uq_users_email     UNIQUE (email),
    CONSTRAINT ck_users_email_len CHECK (char_length(email) >= 3)
);
CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

-- ============================================================================
-- 2. REFRESH TOKENS
-- ============================================================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    token_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    token_hash  VARCHAR(255)  NOT NULL,
    expires_at  TIMESTAMP     NOT NULL,
    revoked_at  TIMESTAMP,
    device_info VARCHAR(300),
    created_at  TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user ON refresh_tokens (user_id);

-- ============================================================================
-- 3. INSTRUMENTS  (reference table — SMALLINT PK with explicit ids)
-- ============================================================================
CREATE TABLE IF NOT EXISTS instruments (
    instrument_id SMALLINT     PRIMARY KEY,
    symbol        VARCHAR(20)  NOT NULL,
    exchange      VARCHAR(10)  NOT NULL,
    lot_size      INTEGER      NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_instruments_symbol   UNIQUE (symbol),
    CONSTRAINT ck_instruments_exchange CHECK (exchange IN ('NSE', 'BSE')),
    CONSTRAINT ck_instruments_lot_size CHECK (lot_size > 0)
);

-- Seed NIFTY50 (NSE) and SENSEX (BSE) — idempotent
INSERT INTO instruments (instrument_id, symbol, exchange, lot_size, is_active)
VALUES (1, 'NIFTY50', 'NSE', 65, TRUE),
       (2, 'SENSEX',  'BSE', 20, TRUE)
ON CONFLICT (instrument_id) DO NOTHING;

-- ============================================================================
-- 4. INDEX LIVE DATA  (append-only 1-min snapshots)
-- ============================================================================
CREATE TABLE IF NOT EXISTS index_live_data (
    row_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id SMALLINT      NOT NULL,
    trade_date    DATE          NOT NULL,
    snap_ts       TIMESTAMP     NOT NULL,
    last_price    NUMERIC(12,2) NOT NULL,
    open_price    NUMERIC(12,2),
    high_price    NUMERIC(12,2),
    low_price     NUMERIC(12,2),
    prev_close    NUMERIC(12,2),
    change_pct    NUMERIC(7,3),
    volume        BIGINT,
    india_vix     NUMERIC(7,3),

    CONSTRAINT fk_ild_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id),
    CONSTRAINT ck_ild_prices CHECK (
        last_price > 0
        AND (high_price IS NULL OR low_price IS NULL OR high_price >= low_price)
    ),
    CONSTRAINT ck_ild_india_vix CHECK (india_vix IS NULL OR india_vix > 0)
);
CREATE INDEX IF NOT EXISTS ix_index_live_data_lookup
    ON index_live_data (instrument_id, trade_date, snap_ts);

-- ============================================================================
-- 5. OPTION CHAIN SNAPSHOTS  (parent of option_chain_rows)
-- ============================================================================
CREATE TABLE IF NOT EXISTS option_chain_snapshots (
    snapshot_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id   SMALLINT      NOT NULL,
    trade_date      DATE          NOT NULL,
    expiry_date     DATE          NOT NULL,
    snap_ts         TIMESTAMP     NOT NULL,
    spot            NUMERIC(12,2) NOT NULL,
    atm_strike      NUMERIC(12,2) NOT NULL,
    total_call_oi   BIGINT,
    total_put_oi    BIGINT,
    pcr_oi          NUMERIC(8,4),
    pcr_volume      NUMERIC(8,4),
    max_pain_strike NUMERIC(12,2),

    CONSTRAINT fk_ocs_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id),
    CONSTRAINT ck_ocs_spot   CHECK (spot > 0),
    CONSTRAINT ck_ocs_expiry CHECK (expiry_date >= trade_date),
    CONSTRAINT ck_ocs_pcr    CHECK (pcr_oi IS NULL OR pcr_oi >= 0)
);
CREATE INDEX IF NOT EXISTS ix_oc_snapshots_lookup
    ON option_chain_snapshots (instrument_id, trade_date, snap_ts);

-- ============================================================================
-- 6. OPTION CHAIN ROWS  (per-strike detail; cascade-deleted with snapshot)
-- ============================================================================
CREATE TABLE IF NOT EXISTS option_chain_rows (
    row_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id  BIGINT        NOT NULL,
    trade_date   DATE          NOT NULL,
    strike       NUMERIC(12,2) NOT NULL,
    option_type  CHAR(2)       NOT NULL,
    ltp          NUMERIC(12,2),
    oi           BIGINT,
    oi_change    BIGINT,
    volume       BIGINT,
    iv           NUMERIC(7,3),
    delta        NUMERIC(7,4),
    theta        NUMERIC(9,4),
    vega         NUMERIC(9,4),
    gamma        NUMERIC(9,6),
    buildup_type SMALLINT,   -- 1=LongBuildup 2=ShortBuildup 3=ShortCovering 4=LongUnwinding

    CONSTRAINT fk_ocr_snapshot FOREIGN KEY (snapshot_id)
        REFERENCES option_chain_snapshots (snapshot_id) ON DELETE CASCADE,
    CONSTRAINT ck_ocr_option_type CHECK (option_type IN ('CE', 'PE')),
    CONSTRAINT ck_ocr_buildup CHECK (buildup_type IS NULL OR buildup_type BETWEEN 1 AND 4),
    CONSTRAINT ck_ocr_iv      CHECK (iv IS NULL OR iv > 0),
    CONSTRAINT ck_ocr_strike  CHECK (strike > 0)
);
CREATE INDEX IF NOT EXISTS ix_oc_rows_snap
    ON option_chain_rows (snapshot_id, option_type, strike);

-- ============================================================================
-- 7. INSTITUTIONAL ACTIVITY  (EOD FII/DII)
-- ============================================================================
CREATE TABLE IF NOT EXISTS institutional_activity (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date      DATE           NOT NULL,
    category        VARCHAR(10)    NOT NULL,
    segment         VARCHAR(20)    NOT NULL,
    buy_value_cr    NUMERIC(16,2),
    sell_value_cr   NUMERIC(16,2),
    net_value_cr    NUMERIC(16,2),
    long_contracts  BIGINT,
    short_contracts BIGINT,
    is_provisional  BOOLEAN        NOT NULL DEFAULT TRUE,
    source_ts       TIMESTAMP      NOT NULL,

    CONSTRAINT uq_inst UNIQUE (trade_date, category, segment, is_provisional),
    CONSTRAINT ck_ia_category CHECK (category IN ('FII', 'DII')),
    CONSTRAINT ck_ia_segment  CHECK (segment IN ('CASH','IDX_FUT','STK_FUT','IDX_OPT','STK_OPT','DEBT'))
);
CREATE INDEX IF NOT EXISTS ix_inst_date_cat
    ON institutional_activity (trade_date, category);

-- ============================================================================
-- 8. NEWS FEED  (deduplicated)
-- ============================================================================
CREATE TABLE IF NOT EXISTS news_feed (
    news_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       VARCHAR(80)   NOT NULL,
    headline     VARCHAR(500)  NOT NULL,
    url          VARCHAR(800),
    published_at TIMESTAMP     NOT NULL,
    dedup_hash   CHAR(64)      NOT NULL,
    category     VARCHAR(40),
    ingested_at  TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT uq_news_dedup UNIQUE (dedup_hash),
    CONSTRAINT ck_news_category CHECK (category IS NULL OR category IN (
        'RBI','MACRO','GLOBAL','EARNINGS','INDEX','CORPORATE','GEOPOLITICAL'
    ))
);
CREATE INDEX IF NOT EXISTS ix_news_pub ON news_feed (published_at);

-- ============================================================================
-- 9. MARKET SENTIMENT  (instrument_id nullable = market-wide)
-- ============================================================================
CREATE TABLE IF NOT EXISTS market_sentiment (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id SMALLINT,
    as_of         TIMESTAMP    NOT NULL,
    model         VARCHAR(40)  NOT NULL,
    label         SMALLINT     NOT NULL,   -- -1 | 0 | 1
    score         NUMERIC(6,4) NOT NULL,
    confidence    NUMERIC(6,4) NOT NULL,
    rationale     VARCHAR(1000),

    CONSTRAINT fk_ms_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id) ON DELETE SET NULL,
    CONSTRAINT ck_ms_label      CHECK (label IN (-1, 0, 1)),
    CONSTRAINT ck_ms_score      CHECK (score BETWEEN -1.0 AND 1.0),
    CONSTRAINT ck_ms_confidence CHECK (confidence BETWEEN 0.0 AND 1.0)
);
CREATE INDEX IF NOT EXISTS ix_sentiment_asof
    ON market_sentiment (instrument_id, as_of);

-- ============================================================================
-- 10. SMART MONEY SIGNALS
-- ============================================================================
CREATE TABLE IF NOT EXISTS smart_money_signals (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id SMALLINT     NOT NULL,
    as_of         TIMESTAMP    NOT NULL,
    signal_type   SMALLINT     NOT NULL,   -- 1..6
    strike        NUMERIC(12,2),
    option_type   CHAR(2),
    strength      NUMERIC(6,4) NOT NULL,
    confidence    NUMERIC(6,4) NOT NULL,
    evidence      TEXT,                     -- JSON (see Part 2: migrate to JSONB)

    CONSTRAINT fk_sms_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id),
    CONSTRAINT ck_sms_signal_type CHECK (signal_type BETWEEN 1 AND 6),
    CONSTRAINT ck_sms_option_type CHECK (option_type IS NULL OR option_type IN ('CE','PE')),
    CONSTRAINT ck_sms_strength    CHECK (strength BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_sms_confidence  CHECK (confidence BETWEEN 0.0 AND 1.0)
);
CREATE INDEX IF NOT EXISTS ix_sm_asof
    ON smart_money_signals (instrument_id, as_of);

-- ============================================================================
-- 11. AI TRADE SIGNALS
-- ============================================================================
CREATE TABLE IF NOT EXISTS ai_trade_signals (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id   SMALLINT     NOT NULL,
    as_of           TIMESTAMP    NOT NULL,
    bias            SMALLINT     NOT NULL,   -- 1 | 0 | -1
    entry_ref       NUMERIC(12,2),
    stop_ref        NUMERIC(12,2),
    target_ref      NUMERIC(12,2),
    risk_reward     NUMERIC(6,2),
    confidence      NUMERIC(6,4) NOT NULL,
    reasoning       TEXT,
    disclosure_mode VARCHAR(20)  NOT NULL DEFAULT 'intelligence',
    model_version   VARCHAR(30)  NOT NULL,

    CONSTRAINT fk_ats_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id),
    CONSTRAINT ck_ats_bias       CHECK (bias IN (-1, 0, 1)),
    CONSTRAINT ck_ats_confidence CHECK (confidence BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_ats_rr         CHECK (risk_reward IS NULL OR risk_reward >= 0)
);
CREATE INDEX IF NOT EXISTS ix_ai_signals_asof
    ON ai_trade_signals (instrument_id, as_of);

-- ============================================================================
-- 12. SIGNAL OUTCOMES  (accuracy tracking — closes the feedback loop)
-- ============================================================================
CREATE TABLE IF NOT EXISTS signal_outcomes (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id     BIGINT       NOT NULL,
    instrument_id SMALLINT     NOT NULL,
    bias          SMALLINT     NOT NULL,   -- 1 | 0 | -1
    status        VARCHAR(12)  NOT NULL,   -- OPEN|WIN|LOSS|EXPIRED|NEUTRAL
    realized_r    NUMERIC(8,3),
    exit_price    NUMERIC(12,2),
    bars_held     INTEGER,
    signal_as_of  TIMESTAMP    NOT NULL,
    evaluated_at  TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT uq_outcome_signal   UNIQUE (signal_id),
    CONSTRAINT fk_outcome_signal   FOREIGN KEY (signal_id)
        REFERENCES ai_trade_signals (id),
    CONSTRAINT fk_outcome_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id)
);
CREATE INDEX IF NOT EXISTS ix_outcome_lookup ON signal_outcomes (instrument_id, status);
CREATE INDEX IF NOT EXISTS ix_outcome_signal ON signal_outcomes (signal_id);

-- ============================================================================
-- 13. AUDIT LOGS  (append-only)
-- ============================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    as_of   TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    user_id BIGINT,
    action  VARCHAR(80)  NOT NULL,
    ip      VARCHAR(45),
    detail  TEXT,                          -- JSON (see Part 2: migrate to JSONB)

    CONSTRAINT fk_audit_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_audit_user   ON audit_logs (user_id, as_of);
CREATE INDEX IF NOT EXISTS ix_audit_action ON audit_logs (action, as_of);


-- ============================================================================
-- VIEWS
-- ============================================================================

-- V01: latest index snapshot per instrument
CREATE OR REPLACE VIEW vw_latest_index_snapshot AS
SELECT DISTINCT ON (ld.instrument_id)
    i.symbol, i.exchange, ld.instrument_id, ld.trade_date, ld.snap_ts,
    ld.last_price, ld.open_price, ld.high_price, ld.low_price,
    ld.prev_close, ld.change_pct, ld.volume, ld.india_vix
FROM index_live_data ld
JOIN instruments i ON i.instrument_id = ld.instrument_id
ORDER BY ld.instrument_id, ld.snap_ts DESC, ld.row_id DESC;

-- V02: latest option chain header per instrument
CREATE OR REPLACE VIEW vw_latest_option_snapshot AS
SELECT DISTINCT ON (ocs.instrument_id)
    i.symbol, ocs.instrument_id, ocs.snapshot_id, ocs.trade_date,
    ocs.expiry_date, ocs.snap_ts, ocs.spot, ocs.atm_strike,
    ocs.total_call_oi, ocs.total_put_oi, ocs.pcr_oi, ocs.pcr_volume,
    ocs.max_pain_strike
FROM option_chain_snapshots ocs
JOIN instruments i ON i.instrument_id = ocs.instrument_id
ORDER BY ocs.instrument_id, ocs.snap_ts DESC, ocs.snapshot_id DESC;

-- V03: daily FII/DII institutional summary
CREATE OR REPLACE VIEW vw_daily_institutional_summary AS
SELECT
    trade_date,
    MAX(net_value_cr)    FILTER (WHERE category='FII' AND segment='CASH')    AS fii_cash_net_cr,
    MAX(net_value_cr)    FILTER (WHERE category='DII' AND segment='CASH')    AS dii_cash_net_cr,
    MAX(net_value_cr)    FILTER (WHERE category='FII' AND segment='IDX_FUT') AS fii_idx_fut_net_cr,
    MAX(long_contracts)  FILTER (WHERE category='FII' AND segment='IDX_FUT') AS fii_long_contracts,
    MAX(short_contracts) FILTER (WHERE category='FII' AND segment='IDX_FUT') AS fii_short_contracts,
    bool_or(is_provisional) AS is_provisional,
    MAX(source_ts)          AS last_updated
FROM institutional_activity
GROUP BY trade_date;


-- ============================================================================
-- MAINTENANCE FUNCTIONS  (run manually or via pg_cron / OS scheduler)
-- ============================================================================

-- F01: purge expired/revoked refresh tokens older than N days
CREATE OR REPLACE FUNCTION fn_cleanup_expired_tokens(retention_days INT DEFAULT 7)
RETURNS INTEGER AS $$
DECLARE
    cutoff  TIMESTAMP := (now() AT TIME ZONE 'utc') - make_interval(days => retention_days);
    deleted INTEGER;
BEGIN
    DELETE FROM refresh_tokens
    WHERE expires_at < cutoff
       OR (revoked_at IS NOT NULL AND revoked_at < cutoff);
    GET DIAGNOSTICS deleted = ROW_COUNT;
    RETURN deleted;
END;
$$ LANGUAGE plpgsql;

-- F02: purge intraday snapshots older than N days (option rows cascade)
CREATE OR REPLACE FUNCTION fn_purge_old_snapshots(retain_days INT DEFAULT 30)
RETURNS INTEGER AS $$
DECLARE
    cutoff  DATE := ((now() AT TIME ZONE 'utc')::date - retain_days);
    deleted INTEGER;
    total   INTEGER := 0;
BEGIN
    DELETE FROM option_chain_snapshots WHERE trade_date < cutoff;
    GET DIAGNOSTICS deleted = ROW_COUNT; total := total + deleted;

    DELETE FROM index_live_data WHERE trade_date < cutoff;
    GET DIAGNOSTICS deleted = ROW_COUNT; total := total + deleted;

    RETURN total;
END;
$$ LANGUAGE plpgsql;

-- Usage:
--   SELECT fn_cleanup_expired_tokens(7);
--   SELECT fn_purge_old_snapshots(30);


/*
================================================================================
  PART 2 — OPTIONAL POSTGRESQL IMPROVEMENTS (apply via Alembic, not here)
================================================================================
  These are the scaling upgrades discussed during the MSSQL → PostgreSQL move.
  They are intentionally NOT baked into the script above so it stays a faithful
  1:1 of the current ORM. Apply them as a follow-up migration:

  1. JSONB instead of TEXT for JSON columns (queryable + indexable):
       ALTER TABLE smart_money_signals ALTER COLUMN evidence TYPE JSONB USING evidence::jsonb;
       ALTER TABLE audit_logs          ALTER COLUMN detail   TYPE JSONB USING detail::jsonb;

  2. Timezone-aware timestamps (the app stores UTC; make it explicit):
       -- change DateTime -> DateTime(timezone=True) in models.py, then
       ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ
            USING created_at AT TIME ZONE 'utc';
       -- ...repeat for every TIMESTAMP column.

  3. VARCHAR instead of CHAR for fixed-code columns (avoid blank-padding):
       ALTER TABLE option_chain_rows   ALTER COLUMN option_type TYPE VARCHAR(2);
       ALTER TABLE smart_money_signals ALTER COLUMN option_type TYPE VARCHAR(2);
       ALTER TABLE news_feed           ALTER COLUMN dedup_hash  TYPE VARCHAR(64);

  4. Range partitioning by trade_date on the high-volume append-only tables
     (index_live_data, option_chain_rows) once row counts exceed a few million.

  5. Schedule maintenance with pg_cron (or Windows Task Scheduler):
       SELECT cron.schedule('cleanup-tokens', '0 3 * * *',  $$SELECT fn_cleanup_expired_tokens(7)$$);
       SELECT cron.schedule('purge-snapshots','0 4 * * 0',  $$SELECT fn_purge_old_snapshots(30)$$);
================================================================================
*/
