/*
================================================================================
  STRIKFIN — PostgreSQL Database Creation Script
  Database : StrikfinDB
  Engine   : PostgreSQL 16+  (tested on 18)
  Driver   : SQLAlchemy 2.0 async + asyncpg  (postgresql+asyncpg://)
  Auth     : role + password (set DB_USER / DB_PASSWORD in backend/.env)
================================================================================

  HOW TO USE (step by step)
  ─────────────────────────
  1. Make sure PostgreSQL 16+ is running and you know the port (default 5432).
  2. Create the database FIRST (this cannot be done from inside it):

         CREATE DATABASE "StrikfinDB";

     (Keep the double quotes — Postgres folds unquoted names to lowercase,
      so quoting preserves the capital S and D used by the app.)

  3. Connect to StrikfinDB, then run THIS script:
         • pgAdmin : select StrikfinDB → Query Tool → open this file → Run (F5)
         • psql    : psql -h localhost -p 5432 -U postgres -d StrikfinDB -f docs/postgres_db_creation.sql

  4. Point the app at it via backend/.env:
         DB_HOST=localhost
         DB_PORT=5432
         DB_NAME=StrikfinDB
         DB_USER=postgres
         DB_PASSWORD=your-postgres-password

  NOTE: In development the backend also auto-creates these tables from the ORM
  (app/db/models.py) on startup, and Alembic manages them in production. This
  script is the manual / reference equivalent and is safe to re-run (every
  statement uses IF NOT EXISTS / ON CONFLICT).

  TABLE INVENTORY (execution order — mirrors app/db/models.py)
  ───────────────────────────────────────────────────────────
  01. users
  02. refresh_tokens
  02b. user_preferences          (1:1 with users — Settings-page state)
  02c. broker_connections        (per-user encrypted vendor tokens)
  03. instruments                (seeded: NIFTY50, SENSEX)
  04. index_live_data
  05. option_chain_snapshots
  06. option_chain_rows
  07. institutional_activity
  08. news_feed
  09. market_sentiment
  10. smart_money_signals
  11. ai_trade_signals
  12. signal_outcomes
  13. audit_logs
  14. MULTI-TENANT (SaaS) — M5:
      permissions · plans · roles · organizations · role_permissions ·
      api_keys · memberships · subscriptions
      (seeded reference data: 13 permissions, 4 roles + grants, 4 plans; + RLS)

  VIEWS
  ─────────────────────────
  V01. vw_latest_index_snapshot
  V02. vw_latest_option_snapshot
  V03. vw_daily_institutional_summary

  FUNCTIONS (maintenance — replace the old T-SQL stored procedures)
  ─────────────────────────
  F01. fn_cleanup_expired_tokens(retention_days INT)
  F02. fn_purge_old_snapshots(retain_days INT)

  DRIFT NOTE: the legacy MSSQL script also had a `market_regime` table +
  `vw_latest_regime` view, but there is no matching ORM model in models.py
  today, so they are intentionally omitted here. Reconcile in "Part 2"
  (re-add the ORM model or formally drop the feature) before relying on it.
================================================================================
*/

-- ============================================================================
-- 1. USERS
-- ============================================================================
CREATE TABLE IF NOT EXISTS users (
    user_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255)  NOT NULL,
    password_hash VARCHAR(255)  NOT NULL,
    display_name  VARCHAR(100),
    phone         VARCHAR(20),
    state         VARCHAR(64),
    auth_provider VARCHAR(20)   NOT NULL DEFAULT 'email',
    is_active     BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    last_login_at TIMESTAMP,

    CONSTRAINT uq_users_email     UNIQUE (email),
    CONSTRAINT ck_users_email_len CHECK (char_length(email) >= 3)
);
CREATE INDEX IF NOT EXISTS ix_users_email ON users (email);

-- Idempotent backfill: CREATE TABLE above is skipped if `users` already exists,
-- so re-running this script on a pre-profile database still adds the Settings-
-- page profile columns rather than silently leaving them behind.
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone         VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS state         VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS auth_provider VARCHAR(20) NOT NULL DEFAULT 'email';

-- ============================================================================
-- 2. REFRESH TOKENS
-- ============================================================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    token_id    BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT        NOT NULL,
    token_hash  VARCHAR(255)  NOT NULL,
    expires_at  TIMESTAMP     NOT NULL,
    revoked_at  TIMESTAMP,
    device_info VARCHAR(300),
    created_at  TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT uq_refresh_tokens_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_refresh_tokens_user ON refresh_tokens (user_id);

-- ============================================================================
-- 2b. USER PREFERENCES  (1:1 with users — Settings-page state, cascade-deleted)
-- ============================================================================
CREATE TABLE IF NOT EXISTS user_preferences (
    user_id            BIGINT       PRIMARY KEY,
    theme              VARCHAR(20),                              -- classic|warm|dark|terminal
    show_chart_tooltip BOOLEAN      NOT NULL DEFAULT TRUE,
    call_put_scheme    VARCHAR(16)  NOT NULL DEFAULT 'classic',  -- classic|inverted
    created_at         TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at         TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT fk_user_preferences_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);

-- ============================================================================
-- 2c. BROKER CONNECTIONS  (per-user encrypted vendor tokens — Fyers today)
-- ============================================================================
-- Access/refresh tokens are Fernet-encrypted (never plaintext). user_id is
-- nullable: the Fyers OAuth callback is unauthenticated, so that row is the
-- implicit single-user/global connection until per-user M5 wiring lands.
CREATE TABLE IF NOT EXISTS broker_connections (
    id                UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id           BIGINT,
    broker            VARCHAR(20)   NOT NULL,           -- fyers | zerodha | …
    access_token_enc  TEXT,
    refresh_token_enc TEXT,
    meta              JSONB         NOT NULL DEFAULT '{}'::jsonb,
    status            VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE|EXPIRED|REVOKED
    generated_at      TIMESTAMP,
    expires_at        TIMESTAMP,
    created_at        TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at        TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT fk_broker_conn_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_broker_conn_user_broker ON broker_connections (user_id, broker);

-- ============================================================================
-- 3. INSTRUMENTS  (reference table — SMALLINT PK with explicit ids)
-- ============================================================================
CREATE TABLE IF NOT EXISTS instruments (
    instrument_id SMALLINT     PRIMARY KEY,
    symbol        VARCHAR(20)  NOT NULL,
    exchange      VARCHAR(10)  NOT NULL,
    lot_size      INTEGER      NOT NULL,
    is_active     BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_instruments_symbol   UNIQUE (symbol),
    CONSTRAINT ck_instruments_exchange CHECK (exchange IN ('NSE', 'BSE')),
    CONSTRAINT ck_instruments_lot_size CHECK (lot_size > 0)
);

-- Rich Instrument-Master columns (added by Alembic debc9e15fc9b + b7c41f9a2d05;
-- idempotent here so this script recreates the full live schema standalone).
-- `expiry_rule` = FUTURES expiry (monthly); `option_expiry_rule` = OPTION
-- cadence (WEEKLY_TUE for NIFTY/SENSEX, MONTHLY_LAST_THU for BANKNIFTY).
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS uid                UUID NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS display_name       VARCHAR(80);
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS segment            VARCHAR(20);
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS instrument_type    VARCHAR(20);
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS underlying         VARCHAR(40);
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS tick_size          NUMERIC(12,4);
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS strike_step        NUMERIC(12,2);
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS expiry_rule        VARCHAR(40);
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS option_expiry_rule VARCHAR(40);
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS vendor_symbols     JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS snapshot_enabled   BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE instruments ADD COLUMN IF NOT EXISTS status             VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

-- Seed NIFTY50 (NSE), SENSEX (BSE), BANKNIFTY (NSE) — idempotent. Rich values
-- (lot/strike/expiry rules, vendor symbols) are upserted by the app on startup
-- from app/instruments/seed.py — the Python-side source of truth.
INSERT INTO instruments (instrument_id, symbol, exchange, lot_size, is_active)
VALUES (1, 'NIFTY50',   'NSE', 65, TRUE),
       (2, 'SENSEX',    'BSE', 20, TRUE),
       (3, 'BANKNIFTY', 'NSE', 30, TRUE)
ON CONFLICT (instrument_id) DO NOTHING;

-- ============================================================================
-- 4. INDEX LIVE DATA  (append-only 1-min snapshots)
-- ============================================================================
CREATE TABLE IF NOT EXISTS index_live_data (
    row_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id SMALLINT      NOT NULL,
    trade_date    DATE          NOT NULL,
    snap_ts       TIMESTAMP     NOT NULL,
    last_price    NUMERIC(12,2) NOT NULL,
    open_price    NUMERIC(12,2),
    high_price    NUMERIC(12,2),
    low_price     NUMERIC(12,2),
    prev_close    NUMERIC(12,2),
    change_pct    NUMERIC(7,3),
    volume        BIGINT,
    india_vix     NUMERIC(7,3),

    CONSTRAINT fk_ild_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id),
    CONSTRAINT ck_ild_prices CHECK (
        last_price > 0
        AND (high_price IS NULL OR low_price IS NULL OR high_price >= low_price)
    ),
    CONSTRAINT ck_ild_india_vix CHECK (india_vix IS NULL OR india_vix > 0)
);
CREATE INDEX IF NOT EXISTS ix_index_live_data_lookup
    ON index_live_data (instrument_id, trade_date, snap_ts);

-- ============================================================================
-- 5. OPTION CHAIN SNAPSHOTS  (parent of option_chain_rows)
--    future_price: tradable current-month FUTURES price captured with the
--    snapshot. Options Lab price overlays (Multi OI & Volume, etc.) plot the
--    FUTURES price — the instrument traders actually deal — not the index spot.
--    Nullable: rows where the futures fetch failed fall back to `spot` on read
--    (see app/services/options_lab_service.py :: _fut_of / get_oi_series).
--    lot_size: the SEBI contract lot IN EFFECT at capture — frozen so a future
--    lot change never rescales historical lot-scaled reads. NULL (pre-column)
--    rows fall back to the instrument master (options_lab_service._lot_of).
-- ============================================================================
CREATE TABLE IF NOT EXISTS option_chain_snapshots (
    snapshot_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id   SMALLINT      NOT NULL,
    trade_date      DATE          NOT NULL,
    expiry_date     DATE          NOT NULL,
    snap_ts         TIMESTAMP     NOT NULL,
    spot            NUMERIC(12,2) NOT NULL,
    future_price    NUMERIC(12,2),
    lot_size        INTEGER,
    atm_strike      NUMERIC(12,2) NOT NULL,
    total_call_oi   BIGINT,
    total_put_oi    BIGINT,
    pcr_oi          NUMERIC(8,4),
    pcr_volume      NUMERIC(8,4),
    max_pain_strike NUMERIC(12,2),

    CONSTRAINT fk_ocs_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id),
    CONSTRAINT ck_ocs_spot         CHECK (spot > 0),
    CONSTRAINT ck_ocs_future_price CHECK (future_price IS NULL OR future_price > 0),
    CONSTRAINT ck_ocs_lot_size     CHECK (lot_size IS NULL OR lot_size > 0),
    CONSTRAINT ck_ocs_expiry       CHECK (expiry_date >= trade_date),
    CONSTRAINT ck_ocs_pcr          CHECK (pcr_oi IS NULL OR pcr_oi >= 0)
);
CREATE INDEX IF NOT EXISTS ix_oc_snapshots_lookup
    ON option_chain_snapshots (instrument_id, trade_date, snap_ts);

-- Idempotent backfill: CREATE TABLE above is skipped if the table already
-- exists, so re-running this script on a pre-future_price database still adds
-- the column (and its check) rather than silently leaving it behind.
ALTER TABLE option_chain_snapshots ADD COLUMN IF NOT EXISTS future_price NUMERIC(12,2);
ALTER TABLE option_chain_snapshots ADD COLUMN IF NOT EXISTS lot_size     INTEGER;
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_ocs_future_price') THEN
        ALTER TABLE option_chain_snapshots
            ADD CONSTRAINT ck_ocs_future_price CHECK (future_price IS NULL OR future_price > 0);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_ocs_lot_size') THEN
        ALTER TABLE option_chain_snapshots
            ADD CONSTRAINT ck_ocs_lot_size CHECK (lot_size IS NULL OR lot_size > 0);
    END IF;
END $$;

-- ============================================================================
-- 6. OPTION CHAIN ROWS  (per-strike detail; cascade-deleted with snapshot)
-- ============================================================================
CREATE TABLE IF NOT EXISTS option_chain_rows (
    row_id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id  BIGINT        NOT NULL,
    trade_date   DATE          NOT NULL,
    strike       NUMERIC(12,2) NOT NULL,
    option_type  CHAR(2)       NOT NULL,
    ltp          NUMERIC(12,2),
    oi           BIGINT,
    oi_change    BIGINT,
    volume       BIGINT,
    iv           NUMERIC(7,3),
    delta        NUMERIC(7,4),
    theta        NUMERIC(9,4),
    vega         NUMERIC(9,4),
    gamma        NUMERIC(9,6),
    buildup_type SMALLINT,   -- 1=LongBuildup 2=ShortBuildup 3=ShortCovering 4=LongUnwinding

    CONSTRAINT fk_ocr_snapshot FOREIGN KEY (snapshot_id)
        REFERENCES option_chain_snapshots (snapshot_id) ON DELETE CASCADE,
    CONSTRAINT ck_ocr_option_type CHECK (option_type IN ('CE', 'PE')),
    CONSTRAINT ck_ocr_buildup CHECK (buildup_type IS NULL OR buildup_type BETWEEN 1 AND 4),
    CONSTRAINT ck_ocr_iv      CHECK (iv IS NULL OR iv > 0),
    CONSTRAINT ck_ocr_strike  CHECK (strike > 0)
);
CREATE INDEX IF NOT EXISTS ix_oc_rows_snap
    ON option_chain_rows (snapshot_id, option_type, strike);

-- ============================================================================
-- 7. INSTITUTIONAL ACTIVITY  (EOD FII/DII)
-- ============================================================================
CREATE TABLE IF NOT EXISTS institutional_activity (
    id              BIGINT         GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date      DATE           NOT NULL,
    category        VARCHAR(10)    NOT NULL,
    segment         VARCHAR(20)    NOT NULL,
    buy_value_cr    NUMERIC(16,2),
    sell_value_cr   NUMERIC(16,2),
    net_value_cr    NUMERIC(16,2),
    long_contracts  BIGINT,
    short_contracts BIGINT,
    is_provisional  BOOLEAN        NOT NULL DEFAULT TRUE,
    source_ts       TIMESTAMP      NOT NULL,

    CONSTRAINT uq_inst UNIQUE (trade_date, category, segment, is_provisional),
    CONSTRAINT ck_ia_category CHECK (category IN ('FII', 'DII')),
    CONSTRAINT ck_ia_segment  CHECK (segment IN ('CASH','IDX_FUT','STK_FUT','IDX_OPT','STK_OPT','DEBT'))
);
CREATE INDEX IF NOT EXISTS ix_inst_date_cat
    ON institutional_activity (trade_date, category);

-- ============================================================================
-- 8. NEWS FEED  (deduplicated)
-- ============================================================================
CREATE TABLE IF NOT EXISTS news_feed (
    news_id      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       VARCHAR(80)   NOT NULL,
    headline     VARCHAR(500)  NOT NULL,
    url          VARCHAR(800),
    published_at TIMESTAMP     NOT NULL,
    dedup_hash   CHAR(64)      NOT NULL,
    category     VARCHAR(40),
    ingested_at  TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT uq_news_dedup UNIQUE (dedup_hash),
    CONSTRAINT ck_news_category CHECK (category IS NULL OR category IN (
        'RBI','MACRO','GLOBAL','EARNINGS','INDEX','CORPORATE','GEOPOLITICAL'
    ))
);
CREATE INDEX IF NOT EXISTS ix_news_pub ON news_feed (published_at);

-- ============================================================================
-- 9. MARKET SENTIMENT  (instrument_id nullable = market-wide)
-- ============================================================================
CREATE TABLE IF NOT EXISTS market_sentiment (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id SMALLINT,
    as_of         TIMESTAMP    NOT NULL,
    model         VARCHAR(40)  NOT NULL,
    label         SMALLINT     NOT NULL,   -- -1 | 0 | 1
    score         NUMERIC(6,4) NOT NULL,
    confidence    NUMERIC(6,4) NOT NULL,
    rationale     VARCHAR(1000),

    CONSTRAINT fk_ms_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id) ON DELETE SET NULL,
    CONSTRAINT ck_ms_label      CHECK (label IN (-1, 0, 1)),
    CONSTRAINT ck_ms_score      CHECK (score BETWEEN -1.0 AND 1.0),
    CONSTRAINT ck_ms_confidence CHECK (confidence BETWEEN 0.0 AND 1.0)
);
CREATE INDEX IF NOT EXISTS ix_sentiment_asof
    ON market_sentiment (instrument_id, as_of);

-- ============================================================================
-- 10. SMART MONEY SIGNALS
-- ============================================================================
CREATE TABLE IF NOT EXISTS smart_money_signals (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id SMALLINT     NOT NULL,
    as_of         TIMESTAMP    NOT NULL,
    signal_type   SMALLINT     NOT NULL,   -- 1..6
    strike        NUMERIC(12,2),
    option_type   CHAR(2),
    strength      NUMERIC(6,4) NOT NULL,
    confidence    NUMERIC(6,4) NOT NULL,
    evidence      TEXT,                     -- JSON (see Part 2: migrate to JSONB)

    CONSTRAINT fk_sms_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id),
    CONSTRAINT ck_sms_signal_type CHECK (signal_type BETWEEN 1 AND 6),
    CONSTRAINT ck_sms_option_type CHECK (option_type IS NULL OR option_type IN ('CE','PE')),
    CONSTRAINT ck_sms_strength    CHECK (strength BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_sms_confidence  CHECK (confidence BETWEEN 0.0 AND 1.0)
);
CREATE INDEX IF NOT EXISTS ix_sm_asof
    ON smart_money_signals (instrument_id, as_of);

-- ============================================================================
-- 11. AI TRADE SIGNALS
-- ============================================================================
CREATE TABLE IF NOT EXISTS ai_trade_signals (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instrument_id   SMALLINT     NOT NULL,
    as_of           TIMESTAMP    NOT NULL,
    bias            SMALLINT     NOT NULL,   -- 1 | 0 | -1
    entry_ref       NUMERIC(12,2),
    stop_ref        NUMERIC(12,2),
    target_ref      NUMERIC(12,2),
    risk_reward     NUMERIC(6,2),
    confidence      NUMERIC(6,4) NOT NULL,
    reasoning       TEXT,
    disclosure_mode VARCHAR(20)  NOT NULL DEFAULT 'intelligence',
    model_version   VARCHAR(30)  NOT NULL,

    CONSTRAINT fk_ats_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id),
    CONSTRAINT ck_ats_bias       CHECK (bias IN (-1, 0, 1)),
    CONSTRAINT ck_ats_confidence CHECK (confidence BETWEEN 0.0 AND 1.0),
    CONSTRAINT ck_ats_rr         CHECK (risk_reward IS NULL OR risk_reward >= 0)
);
CREATE INDEX IF NOT EXISTS ix_ai_signals_asof
    ON ai_trade_signals (instrument_id, as_of);

-- ============================================================================
-- 12. SIGNAL OUTCOMES  (accuracy tracking — closes the feedback loop)
-- ============================================================================
CREATE TABLE IF NOT EXISTS signal_outcomes (
    id            BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    signal_id     BIGINT       NOT NULL,
    instrument_id SMALLINT     NOT NULL,
    bias          SMALLINT     NOT NULL,   -- 1 | 0 | -1
    status        VARCHAR(12)  NOT NULL,   -- OPEN|WIN|LOSS|EXPIRED|NEUTRAL
    realized_r    NUMERIC(8,3),
    exit_price    NUMERIC(12,2),
    bars_held     INTEGER,
    signal_as_of  TIMESTAMP    NOT NULL,
    evaluated_at  TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT uq_outcome_signal   UNIQUE (signal_id),
    CONSTRAINT fk_outcome_signal   FOREIGN KEY (signal_id)
        REFERENCES ai_trade_signals (id),
    CONSTRAINT fk_outcome_instrument FOREIGN KEY (instrument_id)
        REFERENCES instruments (instrument_id)
);
CREATE INDEX IF NOT EXISTS ix_outcome_lookup ON signal_outcomes (instrument_id, status);
CREATE INDEX IF NOT EXISTS ix_outcome_signal ON signal_outcomes (signal_id);

-- ============================================================================
-- 13. AUDIT LOGS  (append-only)
-- ============================================================================
CREATE TABLE IF NOT EXISTS audit_logs (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    as_of   TIMESTAMP    NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    user_id BIGINT,
    action  VARCHAR(80)  NOT NULL,
    ip      VARCHAR(45),
    detail  TEXT,                          -- JSON (see Part 2: migrate to JSONB)

    CONSTRAINT fk_audit_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_audit_user   ON audit_logs (user_id, as_of);
CREATE INDEX IF NOT EXISTS ix_audit_action ON audit_logs (action, as_of);


-- ============================================================================
-- 14. MULTI-TENANT (SaaS) PLANE  — M5
--     plans · organizations · roles · permissions · role_permissions ·
--     memberships · api_keys · subscriptions  (+ seeded reference data + RLS)
-- ============================================================================
-- Every user gets a personal organization on register (owner role, plan 'free').
-- UUID PKs use gen_random_uuid() (built into PostgreSQL 13+). Created/updated
-- timestamps are naive-UTC TIMESTAMP, matching the rest of this schema.

-- 14.1 permissions (reference — seeded below)
CREATE TABLE IF NOT EXISTS permissions (
    id          UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    key         VARCHAR(60)   NOT NULL,
    description VARCHAR(200),

    CONSTRAINT uq_permissions_key UNIQUE (key)
);

-- 14.2 plans (reference — seeded below; price_inr is in PAISE)
CREATE TABLE IF NOT EXISTS plans (
    id        UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    key       VARCHAR(20)   NOT NULL,               -- free|pro|desk|enterprise
    name      VARCHAR(60)   NOT NULL,
    price_inr INTEGER       NOT NULL DEFAULT 0,      -- paise
    limits    JSONB         NOT NULL DEFAULT '{}'::jsonb,
    is_active BOOLEAN       NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_plans_key UNIQUE (key)
);

-- 14.3 roles (reference — seeded below)
CREATE TABLE IF NOT EXISTS roles (
    id        UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    key       VARCHAR(30)   NOT NULL,               -- owner|admin|analyst|viewer
    name      VARCHAR(60)   NOT NULL,
    is_system BOOLEAN       NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_roles_key UNIQUE (key)
);

-- 14.4 organizations (a tenant; personal org per user)
CREATE TABLE IF NOT EXISTS organizations (
    id            UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    name          VARCHAR(120)  NOT NULL,
    slug          VARCHAR(140)  NOT NULL,
    owner_user_id BIGINT        NOT NULL,
    plan_key      VARCHAR(20)   NOT NULL DEFAULT 'free',
    is_personal   BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at    TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    deleted_at    TIMESTAMP,

    CONSTRAINT uq_organizations_slug UNIQUE (slug),
    CONSTRAINT fk_org_owner FOREIGN KEY (owner_user_id)
        REFERENCES users (user_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_org_owner ON organizations (owner_user_id);

-- 14.5 role_permissions (role ↔ permission grants — seeded below)
CREATE TABLE IF NOT EXISTS role_permissions (
    role_id       UUID NOT NULL,
    permission_id UUID NOT NULL,

    CONSTRAINT pk_role_permissions PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role FOREIGN KEY (role_id)
        REFERENCES roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id)
        REFERENCES permissions (id) ON DELETE CASCADE
);

-- 14.6 api_keys (per-org public API plane; only the hash is stored)
CREATE TABLE IF NOT EXISTS api_keys (
    id           UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       UUID          NOT NULL,
    name         VARCHAR(80)   NOT NULL,
    key_prefix   VARCHAR(16)   NOT NULL,
    key_hash     VARCHAR(128)  NOT NULL,
    scopes       JSONB         NOT NULL DEFAULT '[]'::jsonb,
    created_by   BIGINT,
    last_used_at TIMESTAMP,
    revoked_at   TIMESTAMP,
    created_at   TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT uq_api_keys_hash UNIQUE (key_hash),
    CONSTRAINT fk_api_keys_org FOREIGN KEY (org_id)
        REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_api_keys_creator FOREIGN KEY (created_by)
        REFERENCES users (user_id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS ix_api_keys_org ON api_keys (org_id);

-- 14.7 memberships (a user's role within an org)
CREATE TABLE IF NOT EXISTS memberships (
    id         UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id     UUID          NOT NULL,
    user_id    BIGINT        NOT NULL,
    role_id    UUID          NOT NULL,
    status     VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE|INVITED|SUSPENDED
    created_at TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT uq_membership_org_user UNIQUE (org_id, user_id),
    CONSTRAINT fk_membership_org FOREIGN KEY (org_id)
        REFERENCES organizations (id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_role FOREIGN KEY (role_id)
        REFERENCES roles (id)
);
CREATE INDEX IF NOT EXISTS ix_membership_org  ON memberships (org_id);
CREATE INDEX IF NOT EXISTS ix_membership_user ON memberships (user_id);

-- 14.8 subscriptions (an org's current plan; Razorpay staged, not live)
CREATE TABLE IF NOT EXISTS subscriptions (
    id                 UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id             UUID          NOT NULL,
    plan_key           VARCHAR(20)   NOT NULL,
    status             VARCHAR(20)   NOT NULL DEFAULT 'ACTIVE',   -- ACTIVE|PAST_DUE|CANCELED
    provider           VARCHAR(20)   NOT NULL DEFAULT 'manual',   -- manual|razorpay
    provider_ref       VARCHAR(120),
    current_period_end TIMESTAMP,
    created_at         TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    updated_at         TIMESTAMP     NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),

    CONSTRAINT fk_subscriptions_org FOREIGN KEY (org_id)
        REFERENCES organizations (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_subscriptions_org ON subscriptions (org_id);

-- ── 14.9 Seed reference data (idempotent via ON CONFLICT) ───────────────────
INSERT INTO permissions (key, description) VALUES
    ('instrument.read', 'Read instruments, quotes, chains'),
    ('dashboard.read',  'View dashboards'),
    ('options.read',    'View options analytics'),
    ('analytics.read',  'View analytics (OI, gamma, etc.)'),
    ('watchlist.write', 'Create/edit watchlists'),
    ('alert.write',     'Create/edit alerts'),
    ('strategy.write',  'Create/edit strategies'),
    ('journal.write',   'Create/edit journal entries'),
    ('broker.connect',  'Connect a broker account'),
    ('member.manage',   'Invite/remove org members'),
    ('apikey.manage',   'Create/revoke API keys'),
    ('org.manage',      'Manage organization settings'),
    ('org.billing',     'Manage billing & subscription')
ON CONFLICT (key) DO NOTHING;

INSERT INTO roles (key, name, is_system) VALUES
    ('owner',   'Owner',   TRUE),
    ('admin',   'Admin',   TRUE),
    ('analyst', 'Analyst', TRUE),
    ('viewer',  'Viewer',  TRUE)
ON CONFLICT (key) DO NOTHING;

INSERT INTO plans (key, name, price_inr, limits) VALUES
    ('free',       'Free',       0,      '{"watchlists":1,"alerts":3,"api_keys":0,"live_data":false}'),
    ('pro',        'Pro',        49900,  '{"watchlists":25,"alerts":100,"api_keys":2,"live_data":true}'),
    ('desk',       'Desk',       249900, '{"watchlists":200,"alerts":1000,"api_keys":10,"live_data":true}'),
    ('enterprise', 'Enterprise', 0,      '{"watchlists":-1,"alerts":-1,"api_keys":-1,"live_data":true}')
ON CONFLICT (key) DO NOTHING;

-- Role → permission grants (cumulative: viewer ⊂ analyst ⊂ admin ⊂ owner).
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r, permissions p WHERE
    (r.key = 'viewer'  AND p.key IN ('instrument.read','dashboard.read','options.read','analytics.read'))
 OR (r.key = 'analyst' AND p.key IN ('instrument.read','dashboard.read','options.read','analytics.read',
                                     'watchlist.write','alert.write','strategy.write','journal.write','broker.connect'))
 OR (r.key = 'admin'   AND p.key IN ('instrument.read','dashboard.read','options.read','analytics.read',
                                     'watchlist.write','alert.write','strategy.write','journal.write','broker.connect',
                                     'member.manage','apikey.manage'))
 OR (r.key = 'owner'   AND p.key IN ('instrument.read','dashboard.read','options.read','analytics.read',
                                     'watchlist.write','alert.write','strategy.write','journal.write','broker.connect',
                                     'member.manage','apikey.manage','org.manage','org.billing'))
ON CONFLICT DO NOTHING;

-- ── 14.10 Row-Level Security (deploy-ready tenant isolation) ─────────────────
-- Policies key on the per-request GUC app.tenant_id (set by get_db). The app
-- currently connects as a superuser role, which BYPASSES RLS — so app-layer
-- scoping is the live enforcement; these policies activate under a non-superuser
-- role. The NULL/'' branch keeps system/bootstrap queries (no tenant set) working.
-- DROP + CREATE keeps this block idempotent (CREATE POLICY has no IF NOT EXISTS).
DO $$
DECLARE
    t   TEXT;
    col TEXT;
    tenant_tables CONSTANT TEXT[][] := ARRAY[
        ['organizations','id'], ['memberships','org_id'],
        ['api_keys','org_id'],  ['subscriptions','org_id']
    ];
    i INT;
BEGIN
    FOR i IN 1 .. array_length(tenant_tables, 1) LOOP
        t   := tenant_tables[i][1];
        col := tenant_tables[i][2];
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', t || '_tenant_isolation', t);
        EXECUTE format($f$
            CREATE POLICY %I ON %I USING (
                current_setting('app.tenant_id', true) IS NULL
                OR current_setting('app.tenant_id', true) = ''
                OR %I = current_setting('app.tenant_id', true)::uuid
            )$f$, t || '_tenant_isolation', t, col);
    END LOOP;
END $$;


-- ============================================================================
-- VIEWS
-- ============================================================================

-- V01: latest index snapshot per instrument
CREATE OR REPLACE VIEW vw_latest_index_snapshot AS
SELECT DISTINCT ON (ld.instrument_id)
    i.symbol, i.exchange, ld.instrument_id, ld.trade_date, ld.snap_ts,
    ld.last_price, ld.open_price, ld.high_price, ld.low_price,
    ld.prev_close, ld.change_pct, ld.volume, ld.india_vix
FROM index_live_data ld
JOIN instruments i ON i.instrument_id = ld.instrument_id
ORDER BY ld.instrument_id, ld.snap_ts DESC, ld.row_id DESC;

-- V02: latest option chain header per instrument
CREATE OR REPLACE VIEW vw_latest_option_snapshot AS
SELECT DISTINCT ON (ocs.instrument_id)
    i.symbol, ocs.instrument_id, ocs.snapshot_id, ocs.trade_date,
    ocs.expiry_date, ocs.snap_ts, ocs.spot, ocs.future_price, ocs.lot_size,
    ocs.atm_strike,
    ocs.total_call_oi, ocs.total_put_oi, ocs.pcr_oi, ocs.pcr_volume,
    ocs.max_pain_strike
FROM option_chain_snapshots ocs
JOIN instruments i ON i.instrument_id = ocs.instrument_id
ORDER BY ocs.instrument_id, ocs.snap_ts DESC, ocs.snapshot_id DESC;

-- V03: daily FII/DII institutional summary
CREATE OR REPLACE VIEW vw_daily_institutional_summary AS
SELECT
    trade_date,
    MAX(net_value_cr)    FILTER (WHERE category='FII' AND segment='CASH')    AS fii_cash_net_cr,
    MAX(net_value_cr)    FILTER (WHERE category='DII' AND segment='CASH')    AS dii_cash_net_cr,
    MAX(net_value_cr)    FILTER (WHERE category='FII' AND segment='IDX_FUT') AS fii_idx_fut_net_cr,
    MAX(long_contracts)  FILTER (WHERE category='FII' AND segment='IDX_FUT') AS fii_long_contracts,
    MAX(short_contracts) FILTER (WHERE category='FII' AND segment='IDX_FUT') AS fii_short_contracts,
    bool_or(is_provisional) AS is_provisional,
    MAX(source_ts)          AS last_updated
FROM institutional_activity
GROUP BY trade_date;


-- ============================================================================
-- MAINTENANCE FUNCTIONS  (run manually or via pg_cron / OS scheduler)
-- ============================================================================

-- F01: purge expired/revoked refresh tokens older than N days
CREATE OR REPLACE FUNCTION fn_cleanup_expired_tokens(retention_days INT DEFAULT 7)
RETURNS INTEGER AS $$
DECLARE
    cutoff  TIMESTAMP := (now() AT TIME ZONE 'utc') - make_interval(days => retention_days);
    deleted INTEGER;
BEGIN
    DELETE FROM refresh_tokens
    WHERE expires_at < cutoff
       OR (revoked_at IS NOT NULL AND revoked_at < cutoff);
    GET DIAGNOSTICS deleted = ROW_COUNT;
    RETURN deleted;
END;
$$ LANGUAGE plpgsql;

-- F02: purge intraday snapshots older than N days (option rows cascade)
CREATE OR REPLACE FUNCTION fn_purge_old_snapshots(retain_days INT DEFAULT 30)
RETURNS INTEGER AS $$
DECLARE
    cutoff  DATE := ((now() AT TIME ZONE 'utc')::date - retain_days);
    deleted INTEGER;
    total   INTEGER := 0;
BEGIN
    DELETE FROM option_chain_snapshots WHERE trade_date < cutoff;
    GET DIAGNOSTICS deleted = ROW_COUNT; total := total + deleted;

    DELETE FROM index_live_data WHERE trade_date < cutoff;
    GET DIAGNOSTICS deleted = ROW_COUNT; total := total + deleted;

    RETURN total;
END;
$$ LANGUAGE plpgsql;

-- Usage:
--   SELECT fn_cleanup_expired_tokens(7);
--   SELECT fn_purge_old_snapshots(30);


/*
================================================================================
  PART 2 — OPTIONAL POSTGRESQL IMPROVEMENTS (apply via Alembic, not here)
================================================================================
  These are the scaling upgrades discussed during the MSSQL → PostgreSQL move.
  They are intentionally NOT baked into the script above so it stays a faithful
  1:1 of the current ORM. Apply them as a follow-up migration:

  1. JSONB instead of TEXT for JSON columns (queryable + indexable):
       ALTER TABLE smart_money_signals ALTER COLUMN evidence TYPE JSONB USING evidence::jsonb;
       ALTER TABLE audit_logs          ALTER COLUMN detail   TYPE JSONB USING detail::jsonb;

  2. Timezone-aware timestamps (the app stores UTC; make it explicit):
       -- change DateTime -> DateTime(timezone=True) in models.py, then
       ALTER TABLE users ALTER COLUMN created_at TYPE TIMESTAMPTZ
            USING created_at AT TIME ZONE 'utc';
       -- ...repeat for every TIMESTAMP column.

  3. VARCHAR instead of CHAR for fixed-code columns (avoid blank-padding):
       ALTER TABLE option_chain_rows   ALTER COLUMN option_type TYPE VARCHAR(2);
       ALTER TABLE smart_money_signals ALTER COLUMN option_type TYPE VARCHAR(2);
       ALTER TABLE news_feed           ALTER COLUMN dedup_hash  TYPE VARCHAR(64);

  4. Range partitioning by trade_date on the high-volume append-only tables
     (index_live_data, option_chain_rows) once row counts exceed a few million.

  5. Schedule maintenance with pg_cron (or Windows Task Scheduler):
       SELECT cron.schedule('cleanup-tokens', '0 3 * * *',  $$SELECT fn_cleanup_expired_tokens(7)$$);
       SELECT cron.schedule('purge-snapshots','0 4 * * 0',  $$SELECT fn_purge_old_snapshots(30)$$);
================================================================================
*/
